"""initial backend schema

Revision ID: 17dd44bbf165
Revises:
Create Date: 2026-07-29 22:50:50.302606
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "17dd44bbf165"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=80), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=80), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_table(
        "cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pathology_number", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_pathology_number"), "cases", ["pathology_number"], unique=True)
    op.create_table(
        "experiment_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("experiment_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_batches_experiment_date"), "experiment_batches", ["experiment_date"], unique=True
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "field_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("data_type", sa.String(length=24), nullable=False),
        sa.Column("system_key", sa.String(length=64), nullable=True),
        sa.Column("is_core", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "key", name="uq_field_project_key"),
        sa.UniqueConstraint("project_id", "system_key", name="uq_field_project_system_key"),
    )
    op.create_index(
        op.f("ix_field_definitions_project_id"), "field_definitions", ["project_id"], unique=False
    )
    op.create_table(
        "project_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("current_experiment_date", sa.Date(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "project_id", name="uq_record_case_project"),
    )
    op.create_index("ix_record_project_status", "project_records", ["project_id", "status"], unique=False)
    op.create_table(
        "report_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_template_project_name"),
    )
    op.create_table(
        "experiment_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("record_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("experiment_number", sa.String(length=80), nullable=False),
        sa.Column("is_repeat", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["experiment_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["record_id"], ["project_records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "position", name="uq_batch_position"),
        sa.UniqueConstraint("experiment_number", name="uq_experiment_number"),
    )
    op.create_index(op.f("ix_experiment_runs_batch_id"), "experiment_runs", ["batch_id"], unique=False)
    op.create_index(op.f("ix_experiment_runs_record_id"), "experiment_runs", ["record_id"], unique=False)
    op.create_index("ix_run_record_created", "experiment_runs", ["record_id", "created_at"], unique=False)
    op.create_table(
        "field_options",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("field_id", sa.String(length=36), nullable=False),
        sa.Column("value", sa.String(length=240), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["field_definitions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("field_id", "value", name="uq_field_option_value"),
    )
    op.create_index(op.f("ix_field_options_field_id"), "field_options", ["field_id"], unique=False)
    op.create_table(
        "record_values",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("record_id", sa.String(length=36), nullable=False),
        sa.Column("field_id", sa.String(length=36), nullable=False),
        sa.Column("value_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["field_definitions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["record_id"], ["project_records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("record_id", "field_id", name="uq_record_field_value"),
    )
    op.create_index(op.f("ix_record_values_field_id"), "record_values", ["field_id"], unique=False)
    op.create_index(op.f("ix_record_values_record_id"), "record_values", ["record_id"], unique=False)
    op.create_table(
        "report_template_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("template_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=260), nullable=False),
        sa.Column("storage_path", sa.String(length=600), nullable=False),
        sa.Column("placeholders", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["template_id"], ["report_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("template_id", "version_number", name="uq_template_version_number"),
    )
    op.create_index(
        op.f("ix_report_template_versions_template_id"),
        "report_template_versions",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "report_mappings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("template_version_id", sa.String(length=36), nullable=False),
        sa.Column("placeholder", sa.String(length=240), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("field_id", sa.String(length=36), nullable=True),
        sa.Column("fixed_value", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["field_definitions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["template_version_id"], ["report_template_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("template_version_id", "placeholder", name="uq_mapping_version_placeholder"),
    )
    op.create_index(
        op.f("ix_report_mappings_template_version_id"),
        "report_mappings",
        ["template_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_mappings_template_version_id"), table_name="report_mappings")
    op.drop_table("report_mappings")
    op.drop_index(op.f("ix_report_template_versions_template_id"), table_name="report_template_versions")
    op.drop_table("report_template_versions")
    op.drop_index(op.f("ix_record_values_record_id"), table_name="record_values")
    op.drop_index(op.f("ix_record_values_field_id"), table_name="record_values")
    op.drop_table("record_values")
    op.drop_index(op.f("ix_field_options_field_id"), table_name="field_options")
    op.drop_table("field_options")
    op.drop_index("ix_run_record_created", table_name="experiment_runs")
    op.drop_index(op.f("ix_experiment_runs_record_id"), table_name="experiment_runs")
    op.drop_index(op.f("ix_experiment_runs_batch_id"), table_name="experiment_runs")
    op.drop_table("experiment_runs")
    op.drop_table("report_templates")
    op.drop_index("ix_record_project_status", table_name="project_records")
    op.drop_table("project_records")
    op.drop_index(op.f("ix_field_definitions_project_id"), table_name="field_definitions")
    op.drop_table("field_definitions")
    op.drop_table("projects")
    op.drop_index(op.f("ix_experiment_batches_experiment_date"), table_name="experiment_batches")
    op.drop_table("experiment_batches")
    op.drop_index(op.f("ix_cases_pathology_number"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
